# 4ID-B setup

scaler_4idCTR8:
  device: scaler_ctr8
  baseline: True

usb_ctr8:
  device: ctr8
  baseline: True

camera_4idb:
  device: flag_camera_4idb
  baseline: False
  timeout: 5

flags:
  device: flag_4idb
  baseline: True

diamond_window_table:
  device: diamond_window
  baseline: True

table_4idb:
  device: midtable_4idb
  baseline: True

tetramms:
  device: btetramm
  baseline: True

polarimeter:
  device: pol
  baseline: False

jj_slits:
  device: bslt
  baseline: True

filters_device:
  device: bfilter
  baseline: True

chopper_device:
  device: chopper
  baseline: True

kb_mirrors:
  device: kbb
  baseline: True

electromagnet:
  device: emag
  baseline: True
