# Basic beamline devices
# Includes source, optics and auxiliar devices that are relevant to all
# experiments.

id4_common.devices.aps_xbpm.MyXBPM:
- name: aps_xbpm
  prefix: S04
  labels: ["source", "baseline"]

id4_common.devices.aps_undulator.PolarUndulatorPair:
- name: undulators
  prefix: "S04ID:"
  labels: ["source", "energy device", "baseline"]

id4_common.devices.aps_status.StatusAPS:
- name: status_aps
  prefix: ""
  labels: ["source", "status", "baseline"]

id4_common.devices.wb_slit.SlitDevice:
- name: wbslt
  prefix: '4idVDCM:'
  motorsDict: {'hor': 'm9', 'diag': 'm10', 'pitch': 'm11', 'yaw': 'm12'}
  slitnum: 1
  labels: ["4ida", "slit", "baseline"]

id4_common.devices.hhl_mirror.ToroidalMirror:
- name: hhl_mirror
  prefix: "4idHHLM:"
  labels: ["4ida", "mirror", "baseline"]

id4_common.devices.mono_feedback.MonoFeedback:
- name: mono_feedback
  prefix: "4idbSoft:"
  labels: ["monochromator", "feedback", "baseline"]

id4_common.devices.monochromator.MonoDevice:
- name: mono
  prefix: "4idVDCM:"
  labels: ["4ida", "monochromator", "energy device", "baseline"]

id4_common.devices.labjacks.CustomLabJackT7:
- name: labjack_4ida
  prefix: "4idaSoft:LJ:"
  labels: ["4ida", "baseline"]

id4_common.devices.jj_slits.SlitDevice:
- name: monoslt
  PV: "4idVDCM:"
  motorsDict: {top: m14, bot: m13, out: m16, inb: m15}
  slitnum: 2
  labels: ["4ida", "slit", "baseline"]

- name: bslt
  PV: "4idbSoft:"
  motorsDict: {top: m11, bot: m10, out: m13, inb: m12}
  slitnum: 1
  labels: ["4idb", "slit", "baseline"]

# PRs prefix must be without :
id4_common.devices.phaseplates.PRDevice:
- name: pr1
  prefix: "4ida"
  prnum: 1
  motorsDict: {x: m1, y: m2, th: m4}
  labels: ["4ida", "phase retarder", "energy device", "track_energy", "baseline"]

- name: pr2
  prefix: "4ida"
  prnum: 2
  motorsDict: {x: m6, y: m7, th: m9}
  labels: ["4ida", "phase retarder", "energy device", "track_energy", "baseline"]

id4_common.devices.phaseplates.PRDeviceBase:
- name: pr3
  prefix: "4ida"
  motorsDict: {x: m10, y: m11, th: m12}
  labels: ["4ida", "phase retarder", "energy device", "track_energy", "baseline"]

id4_common.devices.energy_device.EnergySignal:
- name: energy
  value: 10
  kind: hinted
  labels: ["energy device", "baseline"]

id4_common.devices.qxscan_device.QxscanParams:
- name: qxscan_setup
  labels: ["qxscan", "energy device", "baseline"]

id4_common.devices.polar_status.Status4ID:
- name: status_polar
  prefix: "PA:04ID:"
  labels: ["status", "baseline"]

id4_common.devices.shutters.PolarShutter:
- name: ashutter
  prefix: ""
  state_pv: "S04ID-PSS:StaA:BeamPresent:CM"
  open_pv: "S04ID-PSS:FES:OpenEPICSC"
  close_pv: "S04ID-PSS:FES:CloseEPICSC"
  labels: ["4ida", "shutter", "baseline"]

apstools.devices.ApsPssShutterWithStatus:
- name: bshutter
  prefix: ""
  state_pv: "S04ID-PSS:StaB:BeamPresent:CM"
  open_pv: "S04ID-PSS:SBS:OpenEPICSC"
  close_pv: "S04ID-PSS:SBS:CloseEPICSC"
  labels: ["4idb", "shutter", "baseline"]

# id4_common.devices.scaler_dual_ctr8.DualCTR8Scaler:
# - name: scaler
#   prefix1: "4idCTR8_1:scaler1"
#   prefix2: "4idCTR8_1:scaler2"
#   labels: ["detector", "scaler", "4idb", "4idg", "4idh"]

id4_common.devices.scaler.LocalScalerCH:
- name: scaler1
  prefix: "4idCTR8_1:scaler1"
  labels: ["detector", "scaler", "4idb", "4idg", "4idh"]

- name: scaler2
  prefix: "4idCTR8_1:scaler2"
  labels: ["detector", "scaler", "4idb", "4idg", "4idh"]

id4_common.devices.usb_ctr8.CustomMeasCompCtr:
- name: ctr8
  prefix: "4idCTR8_1:"
  labels: ["detector", "4idb", "4idg", "4idh", "baseline"]

id4_common.devices.polarimeter.PolAnalyzer:
- name: pol
  prefix: "4idbSoft:"
  labels: ["4idb", "baseline"]

id4_common.devices.diamond_window_table.WindowStages:
- name: diamond_window
  prefix: "4idbSoft:"
  labels: ["4ida", "baseline"]

id4_common.devices.table_4idb.Table4idb:
- name: midtable_4idb
  prefix: "4idbSoft:"
  labels: ["4idb", "baseline"]

id4_common.devices.mirror_toroidal.ToroidalMirror:
- name: "t_mirror"
  prefix: "4idbToro:"
  labels: ["4idb", "optics", "mirror", "baseline"]
