# Configuration for the Bluesky instrument package.

# identify the version of this iconfig.yml file
ICONFIG_VERSION: 2.0.0

# Add additional configuration for use with your instrument.
STATION: &station dev

### The short name for the databroker catalog.
DATABROKER_CATALOG: &databroker_catalog 4id_polar

### RunEngine configuration
RUN_ENGINE:
    DEFAULT_METADATA:
        beamline_id: 4id-polar
        instrument_name: *station
        proposal_id: commissioning
        databroker_catalog: *databroker_catalog

    ### EPICS PV to use for the `scan_id`.
    ### Default: `RE.md["scan_id"]` (not using an EPICS PV)
    # SCAN_ID_PV: "IOC:bluesky_scan_id"

    ### Where to "autosave" the RE.md dictionary.
    ### Defaults:
    MD_PATH: /home/beams/POLAR/.config/Bluesky_RunEngine_md_dev

    ### The progress bar is nice to see,
    ### except when it clutters the output in Jupyter notebooks.
    ### Default: False
    USE_PROGRESS_BAR: true

### Best Effort Callback Configurations
### Defaults: all true
### except no plots in queueserver
BEC:
    BASELINE: true
    HEADING: true
    PLOTS: false
    TABLE: true

### APS Data Management
### Use bash shell, deactivate all conda environments, source this file:
DM_SETUP_FILE: /home/dm/etc/dm.setup.sh
DM_ROOT_PATH: /gdata/dm/4IDD
DM_USE_PATH: true

DSERV_ROOT_PATH: &dserv_root /net/s4data/export/sector4/4idd

AREA_DETECTOR:
    # TODO: switch to the Voyager-based path structure: "/gdata/..."
    HDF5_FILE_TEMPLATE: "%s/%s_%6.6d"
    HDF5_FILE_EXTENSION: h5
    EIGER_1M:
        # BLUESKY_FILES_ROOT: /gdata/dm/4IDD/  # forced to be the same
        # IOC_FILES_ROOT: /gdata/dm/4IDD  # unnecessary, uses DM or EPICS value
        DEFAULT_FOLDER: /net/s4data/export/sector4/4idd/bluesky_images/eiger1M
        ALLOW_PLUGIN_WARMUP: true
    VORTEX:
        # BLUESKY_FILES_ROOT: /net/s4data/export/sector4/4idd  # forced to be the same
        IOC_FILES_ROOT: /net/s4data/export/sector4/4idd
        DEFAULT_FOLDER: /net/s4data/export/sector4/4idd/bluesky_images/vortex
        ALLOW_PLUGIN_WARMUP: true
    LIGHTFIELD:
        IOC_FILES_ROOT: Z:\4idd
        BLUESKY_FILES_ROOT: *dserv_root
        RELATIVE_DEFAULT_FOLDER: bluesky_images/spectrometer
        ALLOW_PLUGIN_WARMUP: true
    VIMBA:
        IOC_FILES_ROOT: *dserv_root
        RELATIVE_DEFAULT_FOLDER: bluesky_images/vimba
        ALLOW_PLUGIN_WARMUP: true

### Support for known output file formats.
### Uncomment to use.  If undefined, will not write that type of file.
### Each callback should apply its configuration from here.
NEXUS_DATA_FILES:
    ENABLE: false
    FILE_EXTENSION: hdf

SPEC_DATA_FILES:
    # ENABLE: false
    ENABLE: true
    FILE_EXTENSION: dat

### APS Data Management
### Use bash shell, deactivate all conda environments, source this file:
DM_SETUP_FILE: "/home/dm/etc/dm.setup.sh"

# ----------------------------------

OPHYD:
    ### Control layer for ophyd to communicate with EPICS.
    ### Default: PyEpics
    ### Choices: "PyEpics" or "caproto"
    CONTROL_LAYER: PyEpics

    ### default timeouts (seconds)
    TIMEOUTS:
        PV_READ: &TIMEOUT 5
        PV_WRITE: *TIMEOUT
        PV_CONNECTION: *TIMEOUT

XMODE_DEBUG_LEVEL: Plain
