# Configuration file example for the ptycho-xrf workflow

workflow : ptycho-xrf
experimentName :  Parraga_BDP_Polar2
fit : roi,nnls
filePath : 003003.h5
dataDir : sample02/express3
# nthreads : all
quantifyWith : None
detectors : 3
generateAvgH5 : False
addv9Layout : False
addExchange : False
exportCSV : False
updateTheta : None
updateAmps : None
updateQuantAmps : None
quickAndDirty : False
optimizeFitOverrideParams : None
optimizer : None
analysisMachine : artemis
name : "003003"
sampleName : sample02
ptychoFilePath : scan_003003_eiger1m.hdf5
ptychoDetectorName : eiger
cropCenterXInPixels : None
cropCenterYInPixels : None
cropExtentXInPixels : None
cropExtentYInPixels : None
numGpus : None
probeEnergyInElectronVolts : None
detectorDistanceInMeters : None
preprocessingMachine : artemis
settings : /home/beams/POLAR/ptychodusDefaults/nanomax3003.ini
demand : True
