"""
Utility functions for flyscans
"""

from h5py import File
from numpy import array, empty, where
from logging import getLogger

logger = getLogger(__name__)
logger.info(__file__)

__all__ = """
    read_flyscan_stream
    find_eiger_triggers
""".split()


def read_flyscan_stream(fname, base_key="stream"):
    """Reads stream file generated by PositionerStream"""
    output = {}
    with File(fname, "r") as f:
        for key in f[base_key].keys():
            output[key] = array(f[f"{base_key}/{key}"])
    return output


def find_eiger_triggers(fname, key="Attocube 1 ch. 3"):
    """Finds the points where the Eiger was triggered"""
    dataset = read_flyscan_stream(fname)
    data = empty(dataset[key].size)
    data[1:] = dataset[key][1:] - dataset[key][:-1]
    return where(data == 1)[0]
